### ISSUE TITLE
outDir supported?

### ISSUE THREAD

**Issue by SnappyCroissant** [PanayotCankov/mocha-typescript#15]
Everything works great when compiling .js files side by side with the .ts files but when I set an outDir in tsconfig I get the following:

```
1:22:00 PM - Compilation complete. Watching for file changes.
Run mocha.
Exited with 1
```

Is there a config I'm missing somewhere or is this not supported at the moment?

**Comment by PanayotCankov** [comment]
The typescript compiler and the mocha test runner are executed in separate processes. If you set outDir in the tsconfig the test.js file run by mocha will be placed in the outDir and mocha will fail because it can't find any test files to execute.

You should be able to provide mocha configuration to the watcher (read here https://github.com/PanayotCankov/mocha-typescript/issues/9 ) passing `-o <path to mocha.opts>` and then config the mocha.opts (I am not sure you can change the test file in mocha.opts though).

How would you expect it to work?

**Comment by godart** [comment]
I came across a similar situation.
My suggestion is to have all unparsed parameter forwarded to mocha like this:
`mocha-typescript-watch build/test/`
or
`mocha-typescript-watch build/test/test1.js build/test/test2.js`
